swarmnet:
  devices:
    - ip: 192.168.193.64
      port: 51000
    - ip: 192.168.193.58
      port: 51000
    - ip: 192.168.193.203
      port: 51000
  log_level: warn

agent:
  agent_name: Alice
  initially_this_agents_turn: True
  starting_grid_loc: B3
  starting_grid_heading: north
  ending_grid_loc: B7
  max_num_negotiation_messages: 8
  working_dir: "/home/ubuntu/LLM_ROS2_Control/"
  model: "gpt-4-vision-preview"
  max_tokens: 400

commands:
  forwards: "@FORWARD"
  backwards: "@BACKWARDS"
  rotate_clockwise: "@CLOCKWISE"
  rotate_anticlockwise: "@ANTICLOCKWISE"
  wait: "@WAIT"
  supervisor: "@SUPERVISOR"

movement:
  linear:
    speed: 0.15  # m/s
    distance: 0.50  # m
  angular:
    speed: 45  # deg/s
    distance: 90 # degrees
  waiting_time: 2 # Match time for other movements
  lidar_threshold: 0.3
