swarmnet:
  devices:
    - ip: 10.0.3.1
      port: 51000
    - ip: 10.0.1.112
      port: 51000
    - ip: 10.0.1.192
      port: 51000
  log_level: warn

agent:
  agent_name: Bob
  initially_this_agents_turn: False
  starting_grid_loc: B7
  starting_grid_heading: south
  ending_grid_loc: B0
  max_num_negotiation_messages: 15
  working_dir: "/home/ubuntu/LLM_ROS2_Control/"
  model: "gpt-3.5-turbo"
  max_tokens: 400

commands:
  forwards: "@FORWARD"
  backwards: "@BACKWARDS"
  rotate_clockwise: "@CLOCKWISE"
  rotate_anticlockwise: "@ANTICLOCKWISE"
  wait: "@WAIT"
  supervisor: "@SUPERVISOR"

movement:
  linear:
    speed: 0.15  # m/s
    distance: 0.30  # m
  angular:
    speed: 45  # deg/s
    distance: 90 # degrees
  waiting_time: 2 # Match time for other movements
  lidar_threshold: 0.3
